apiVersion: v1
kind: ConfigMap
metadata:
  name: sxkjfe
  namespace: sxkj-dev
data:
  nginx.conf: |2

    #user  nobody;
    worker_processes  2;

    #error_log  logs/error.log;
    #pid        logs/nginx.pid;
    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        #access_log  logs/access.log  main;

        sendfile        on;
        client_max_body_size   90m;
        charset utf-8;
        keepalive_timeout  65;
        gzip  on;
        server {
            listen       80;
            server_name   sxkj-dev.skiffenergy.com;
            location / {
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, IPOST, OPTIONS";
                add_header Access-Control-Allow-Headers "Authorization, Origin, X-Requested-With, Content-Type, Accept";

                root   /usr/share/nginx/data/sxkj;
                index  index.html index.htm;
                try_files $uri $uri/ index.html;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
        }
    }
