apiVersion: v1
kind: Service
metadata:
  name: basebe
  namespace: sxkj-dev
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    app: basebe
    tier: backend
